chore: Add dependency analysis plugin (#98)
Add dependency analysis plugin to ensure our dependencies are happy!

diff --git a/.github/workflows/pr-checks.yaml b/.github/workflows/pr-checks.yaml
--- a/.github/workflows/pr-checks.yaml
+++ b/.github/workflows/pr-checks.yaml
@@ -23,5 +23,18 @@ jobs:
       - name: Setup Gradle
         uses: gradle/gradle-build-action@v2
         with:
-          arguments: check --continue
           cache-read-only: ${{ github.event_name == 'push' && github.ref != 'refs/heads/main' }}
+
+      - name: Run checks
+        run: |
+          ./gradlew check --continue
+
+      - name: Run Build Health
+        run: |
+          ./gradlew buildHealth --continue
+          # if 'build-health-report.txt' is not empty, fail and echo the content
+          if [ -s build/reports/dependency-analysis/build-health-report.txt ]; then
+              echo "Build health report:"
+              cat build/reports/dependency-analysis/build-health-report.txt
+              exit 1
+          fi
